language: node_js
cache:
  directories:
    - 'node_modules'
jobs:
  include:
    - stage: quality checks
    - script: npm run lint:js
      name: lint files
    - script: npm run lint:licenses
      name: check licenses
