language: node_js
cache:
  directories:
    - 'node_modules'
jobs:
  include:
    - stage: test
      script: npm test
    - stage: lint files
      script: npm run lint:js
    - stage: check licenses
      script: npm lint:licenses
